modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="Tom Wolf - for pushing me to do things I hate, so that I can play things I love. \\n Claycorp for helping my single cell make sense of all of this" #optional
authors="${mod_authors}"
description='''
This tries to solve a long lasting issue of digging some blocks to put your pipes underground.
'''


[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"